services:
  - type: web
    name: render-tailnet-service
    env: docker
    plan: free
    region: frankfurt
    autoDeploy: false
    envVars:
      - key: TAILSCALE_AUTHKEY
        sync: false
      - key: TAILSCALE_VERSION
        value: 1.32.3
